language: node_js
node_js:
- '7'
cache: npm
install:
- npm install newman
deploy:
  provider: heroku
  api_key:
    secure: hzmhen6KXoOH+ZsQz+eBamP9ANFHkpUioqqWfGv6YkJJSz9OjPt1x0SW3hiPETHwzFpI51rckwXqjhjM/sB+VndP9UyYtbiVCvLFANMvGEaFPrJIQZSjiQL0bhaVR8ZAW0B8YoyVLuYZsTw5ZAiLuTN9CzSbpDLbEP8TALhgS/vkohjav6MqTE+Hc6yFEcc5y1r2Wd0SpS83kHzZlzttnki3lQ3RfTDgBJ8b78wdydtKEPKotQRrzxt4F8oo8YeEtua5XKWWwwV4wqWsP5Efuia0uIWtVI4YIjUV8KcPu9iWYsllnNfcFmOOclZMg7eSCwFs+YwhLJWDu7YByzQs96aXAmO+XSTgbxE1qaeHn1nOuD125EJQo6hiR+vhTFh9x5S4pH0SMr3hQ8IJBxPeOMxGMLnSqNxEjn4Cst/YBMp2bHG4l4ZZUvDk8WT57KQ8t4J4Lol9tSf4RoJpBgjr4ilodLQQMeF+BdRU4ShM4gu/upuRoNTLQNMU706MneDdhkrjKCwmAGlrZOd1oNh8EELEObk5PMFLX5FToSgQFNg0WKikZIRjw1yjlZk972X4WJxkSyYdMRVKkvkpnlylOm+dDH9PLmVjfGaqUDmDJtIkLWd9axfrH9DDHmgUUVFUtVoGoFqtHESXpi4ZSjYwX5b26JIeihxmeSCGnCYowys=
  app: xpfarmjs
  on:
    repo: undeadgrishnackh/MathPortal
