language: node_js
node_js:
  - "10"
before_install:
  - npm i -g npm@version-number
cache: npm
"scripts": {
  "test": "npm run cucumber"
}
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master