openapi: 3.0.0
info:
  title: triangle 3th angle calculator
  description: API to calculate the 3th angle of a triangle
  contact:
    email: undeadgrishnackh@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/undeadgrishnackh74/3thAngle/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/undeadgrishnackh74/mathPortal/geometry/triangle/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /3thAngle:
    post:
      tags:
      - admins
      summary: get the 3th angle
      description: Return the 3th angle
      operationId: 3thAngle
      requestBody:
        description: Traingle Angles
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TriangleAngles'
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Triangle3thAngle'
        400:
          description: invalid input, object invalid
components:
  schemas:
    TriangleAngles:
      required:
      - alpha
      - beta
      type: object
      properties:
        alpha:
          type: number
          example: 90
        beta:
          type: number
          example: 45
    Triangle3thAngle:
      type: object
      properties:
        delta:
          type: number
          example: 45
